# 관리자 권한 갖기
sudo: required

# 언어(플랫폼)을 선택
language: generic

# 도커 환경 구성
services:
  - docker

# 스크립트를 실행할 수 있는 환경 구성( Dockerfile을 이용해서 이미지 생성 )
before_install:
  - echo "start Creating an image iwth dockerfile"
  - docker build -t smathj/docker-react-app -f Dockerfile.dev .

# 실행할 스크립트(테스트 실행)
script:
  - docker run -e CI=true smathj/docker-react-app npm run test -- --coverage

# 테스트 성공 후 할일
after_success:
  - echo "Test Success"
