# 관리자 권한 갖기
sudo: required

# 언어(플랫폼)을 선택
language: generic

# 도커 환경 구성
services:
  - docker

# 스크립트를 실행할 수 있는 환경 구성( Dockerfile을 이용해서 이미지 생성  )
before_install:
  - echo "start Creating an image iwth dockerfile"
  - docker build -t smathj/docker-react-app .
  # - docker build -t smathj/docker-react-app -f Dockerfile.dev .

# 실행할 스크립트(테스트 실행)
script:
  # - docker run -e CI=true smathj/docker-react-app npm run test -- --coverage

# Deploy
deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-2'
  app: 'docker-react-app'
  env: 'Dockerreactapp-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-2-526310121710'
  bucket_path: 'docker-react-app'
  on: # 어느 브런치가 push될때마다 할것인지
    branch: main
  # Travis에서 환경변수 access, secret key 가져오기
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
#  테스트 성공 후 할일
# after_success:
#   - echo "Test Success"
